server-rails/config/routes.rb
Rails.application.routes.draw do
  resources :apps
  root 'messages#index'
  resources :messages
  get 'endpoints/deliver/:app_id/:json' => "endpoints#deliver", as: :deliver
  get 'endpoints/register/:app_id/:gcm_id' => "endpoints#register", as: :register

end

server-rails/app/models/app.rb
class App < ActiveRecord::Base
end

server-rails/app/models/message.rb
class Message < ActiveRecord::Base
  def self.delete_queues
    sqs = Aws::SQS::Client.new(region: ENV["AWS_region"])
    queue_urls = sqs.list_queues(queue_name_prefix: QUEUE_NAME_PREFIX).queue_urls
    queue_urls.each do |queue_url|
      sqs.delete_queue(
          queue_url: queue_url
      )
    end
  end
end

server-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

server-rails/app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:app_id, :gcm)
    end
end

server-rails/app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  def deliver
    sqs = Aws::SQS::Client.new(region: ENV["AWS_region"])
    queue_name = QUEUE_NAME_PREFIX + params[:app_id]
    queue_url = sqs.get_queue_url(queue_name: queue_name).queue_url
    sqs.send_message(
      queue_url: queue_url,
      message_body: params[:json]
    )
    redirect_to root_path, notice: "message successfully pushed to queue #{queue_name}"
  end

  def register
    app = App.find_or_create_by(app_id: params[:app_id]) 
    app.update_attributes(gcm_id: params[:gcm_id])
    #create new queue with app_id as name
    sqs = Aws::SQS::Client.new(region: ENV["AWS_region"])
    queue_name = QUEUE_NAME_PREFIX + params[:app_id]
    queue = sqs.create_queue(queue_name: queue_name)
  end

end

server-rails/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    #@messages = Message.all
    sqs = Aws::SQS::Client.new(region: ENV["AWS_region"])
    queue_urls =  sqs.list_queues(queue_name_prefix: QUEUE_NAME_PREFIX).queue_urls.each 
    @queues = []
    queue_urls.each do |queue_url|  
         puts queue_url
         queue = {}
         queue[:queue_url] = queue_url
         queue[:message_count] = sqs.get_queue_attributes({ queue_url: queue_url, attribute_names: ["ApproximateNumberOfMessages"]}).attributes["ApproximateNumberOfMessages"]
         queue[:last_message] = sqs.receive_message({ queue_url: queue_url, max_number_of_messages: 1}).messages
         queue[:last_message] = queue[:last_message][0].nil? ? "-" : queue[:last_message][0].body
         @queues << queue
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create

    @message = Message.new(message_params)

    if @message.save
      #format.html { redirect_to @message, notice: 'Message was successfully created.' }
      #format.json { render :show, status: :created, location: @message }
      #puts message_params
      redirect_to deliver_path(app_id: message_params[:app_id], json: message_params[:json]), notice: 'Message is successfully created'
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:app_id, :json)
    end
end

server-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

server-rails/app/helpers/apps_helper.rb
module AppsHelper
end

server-rails/app/helpers/endpoints_helper.rb
module EndpointsHelper
end

server-rails/app/helpers/messages_helper.rb
module MessagesHelper
end

server-rails/app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.text_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :gcm_id %><br>
    <%= f.text_area :gcm_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server-rails/app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

server-rails/app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apps</h1>

<table>
  <thead>
    <tr>
      <th>App Id</th>
      <th>Gcm Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.app_id %></td>
        <td><%= app.gcm_id %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

server-rails/app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

server-rails/app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @app.app_id %>
</p>

<p>
  <strong>Gcm:</strong>
  <%= @app.gcm_id %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

server-rails/app/views/endpoints/deliver.html.erb
<h1>Endpoints#deliver</h1>
<p>Find me in app/views/endpoints/deliver.html.erb</p>

server-rails/app/views/endpoints/register.html.erb
<h1>Endpoints#register</h1>
<p>Find me in app/views/endpoints/register.html.erb</p>

server-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocalOyeDeliveryServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

server-rails/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.text_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :json %><br>
    <%= f.text_field :json %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server-rails/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

server-rails/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages in queue</h1>

<table style="text-align:center">
  <thead>
    <tr>
      <th>Queue | </th>
      <th>Messages in Queue | </th>
      <th>Next message to be fetched</th>
    </tr>
  </thead>

  <tbody>
    <% @queues.each do |queue| %>
      <tr>
        <td><%= queue[:queue_url] %></td>
        <td><%= queue[:message_count] %></td>
        <td><%= queue[:last_message] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'View Apps', apps_path %>
<%= link_to 'Put New Message in Queue', new_message_path %>

server-rails/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

server-rails/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App:</strong>
  <%= @message.app_id %>
</p>

<p>
  <strong>Json:</strong>
  <%= @message.json %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>